<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\UnifiedCalendar.Core\UnifiedCalendar.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Google.Apis.Calendar.v3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
</Project>
